# numpy

In [1]:
import numpy as np

In [4]:
arr= np.array([1,2,3,4])

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
sum_axis_0 = np.sum(arr)

In [7]:
sum_axis_0

np.int64(10)

In [10]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [11]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.sum(arr_2d , axis = 0)

array([5, 7, 9])

In [13]:
np.sum(arr_2d , axis = 1)

array([ 6, 15])

In [15]:
arr_3d = np.array([
    [[1,2,3],[4,5,6]],
  [[7,8,9],[10,11,12]]])

In [16]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
np.sum(arr_3d , axis =0) #outermost axis -- along the depth

array([[ 8, 10, 12],
       [14, 16, 18]])

In [19]:
np.sum(arr_3d , axis = 1) # along the row

array([[ 5,  7,  9],
       [17, 19, 21]])

In [20]:
np.sum(arr_3d , axis = 2) # along the column

array([[ 6, 15],
       [24, 33]])

In [21]:
arr_3d.shape  # outermost to innermost

(2, 2, 3)

In [34]:
np.linspace(3,8,10) # start  stop step

array([3.        , 3.55555556, 4.11111111, 4.66666667, 5.22222222,
       5.77777778, 6.33333333, 6.88888889, 7.44444444, 8.        ])

In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [39]:
c = np.concatenate([a,b])

In [40]:
c

array([1, 2, 3, 4, 5, 6])

In [42]:
d = np.arange(24)

In [43]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
d.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# pandas

In [3]:
!pip install pandas


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import pandas as pd 

In [6]:
df = pd.read_csv('C:/Users/hp/Downloads/mushrooms.csv') 

In [7]:
print(df.columns)

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')


In [8]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [10]:
df.shape

(8124, 23)

In [11]:
df.sample(6)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
5596     e         f           s         b       t    n               f   
3082     p         x           f         g       f    f               f   
6427     p         f           y         e       f    s               f   
855      e         f           y         n       t    l               f   
2989     e         f           f         n       t    n               f   
2893     e         x           y         e       t    n               f   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
5596            c         b          e  ...                        s   
3082            c         b          g  ...                        k   
6427            c         n          b  ...                        s   
855             c         b          p  ...                        y   
2989            c         b          p  ...                        s   
2893            c         b          p  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
5596                      e                      w         p          w   
3082                      p                      p         p          w   
6427                      w                      w         p          w   
855                       w                      w         p          w   
2989                      w                      w         p          w   
2893                      g                      p         p          w   

     ring-number ring-type spore-print-color population habitat  
5596           t         e                 w          c       w  
3082           o         l                 h          v       p  
6427           o         e                 w          v       l  
855            o         p                 k          s       p  
2989           o         p                 k          v       d  
2893           o         p                 k          v       d  

[6 rows x 23 columns]

In [12]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]